# Site settings
title: peter's blog
description: "Thoughts on life. Technologist, urbanist, cheap eats connoisseur."
baseurl: ""
url: "http://peter.mistermoo.com"
twitter_username: peterkimnyc
github_username: peterskim12

# Build settings
markdown: kramdown
permalink: pretty
